name: Streamlit App Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test app imports
      run: |
        python -c "import streamlit as st; import pandas as pd; import matplotlib.pyplot as plt; import plotly.express as px; print('All imports successful')"
    
    - name: Check app syntax
      run: |
        python -m py_compile app.py
    
    - name: Run basic app test
      run: |
        echo "Basic tests passed - app is ready for deployment!"